### ISSUE TITLE
Bad idea ... kinda

### ISSUE THREAD

**Issue by FredyC** [gaui/react-lazy#1]
Creating lazy component inside another one is problematic as it will be always remounted on each render. 

https://github.com/facebook/react/issues/14299

Sadly, @gaearon decided it's not worth commenting further nor he wants to accept [docs PR](https://github.com/reactjs/reactjs.org/pull/1422) he asked for. Did I really poke into some wasp nest there?

**Comment by theKashey** [comment]
Yep - you have solved it already - https://codesandbox.io/s/mqxzmw4v19

**Comment by gaui** [comment]
@theKashey much better solution! PR or I will update it later. 😊

**Comment by theKashey** [comment]
No hooks in prod yet :(

**Comment by theKashey** [comment]
Does `enzyme` support them? Once I would try to use hooks - they would broke half of existing tests.

**Comment by FredyC** [comment]
> Does `enzyme` support them? Once I would try to use hooks - they would broke half of existing tests.

What do you mean? Personally, I prefer `react-testing-library`, but why it should matter? Do you test rely on implementation details like what is the state? If not, there is nothing special about hooks for testing purposes ... https://egghead.io/lessons/react-test-react-components-that-use-react-hooks

**Comment by FredyC** [comment]
I haven't used Enzyme ever, did not like it so I cannot really relate why and when it would be throwing an exception. I am using RTL with hooks for several weeks now and there is no issue except a little caveat with `useEffect` which needs special `flushEffects` hack.

**Comment by theKashey** [comment]
That's a good thing about RTL - it's based on react own testing tools, while `enzyme` partially emulates them. As a result - does not support new features, when those features got shipped. 💩, quite a big 💩 .
